services:
  rabbitmq:
    image: rabbitmq:4.0.7-management-alpine
    container_name: 'rabbitmq'
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    ports:
        - 5672:5672
        - 15672:15672
        - 15692:15692
    volumes:
        - ./data:/var/lib/rabbitmq
        - ./log:/var/log/rabbitmq
    networks:
        - rabbitmq_net
    restart: always

networks:
  rabbitmq_net:
    name: rabbitmq_net
    driver: bridge

